config/routes.rb
# MiradorAnnotationsServer::Application.routes.draw do
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'annotation_layers#index', to: 'layers',defaults: {format: :json}
  resources :annotation_layers, path: 'layers',defaults: {format: :json}
  resources :annotation_lists, path: 'lists',defaults: {format: :json}
  get '/lists/*url' => 'annotation_lists#show', :format => false
  resources :annotation_lists, path: 'lists', :format => false
  resources :annotations, path: 'annotations',defaults: {format: :json}, :except => [:update]
  put '/annotations', to: 'annotations#update'

  get '/getCanvasData', to: 'services#getLayersListsForCanvas'
  get '/getAnnotations', to: 'annotations#getAnnotationsForCanvas'
  get '/getAnnotationsViaList', to: 'annotations#getAnnotationsForCanvasViaLists'
  get '/resequenceList', to: 'annotation_lists#resequence_list'
  put '/resequenceList', to: 'annotation_lists#resequence_list'
  get '/getSvg', to: 'annotations#getSvg', defaults: {format: :json}
  put '/updateSvg', to: 'annotations#updateSvg', defaults: {format: :json}
  get '/getCanvasForAnno', to: 'annotations#getTargetingAnnosCanvasFromID', defaults: {format: :json}
  get '/getLayersForAnnotation', to: 'annotations#getLayersForAnnotation', defaults: {format: :json}

  post '/setCurrentLayers', to: 'annotation_layers#setCurrentLayers',  defaults: {format: :json}
  post '/createLayerWithGroup', to: 'annotation_layers#createWithGroup', defaults: {format: :json}
  delete 'removeLayerFromGroup', to: 'annotation_layers#remove_layer_from_group', defaults: {format: :json}

  get '/feedAllAnnoIds', to: 'annotations#feedAllAnnoIds', defaults: {format: :text}
  get '/feedAllLayers', to: 'annotations#feedAllLayers', defaults: {format: :text}

  get 'getAccessToken', to: "application#get_access_token", defaults: {format: :json}
  get 'loginToServer', to: "authn#userLogin"

  get 'getAccessToken', to: "application#get_access_token", defaults: {format: :json}
  get 'loginToServer', to: "application#login"

  get 'doRedis', to: "annotations#doRedis"
  get 'setRedisKeys', to: "annotations#setRedisKeys"

  get 'export', to: 'export#export'
  get 'export/check_status', to: 'export#check_status', defaults: {format: :json}
  get 'export/download', to: 'export#download', defaults: {format: :xlsx}

  match '/' => 'application#CORS_preflight', via: [:options], defaults: {format: :json}
  match 'getAccessToken' => 'application#CORS_preflight', via: [:options], defaults: {format: :json}
  match 'getAnnotations' => 'application#CORS_preflight', via: [:options], defaults: {format: :json}
  match 'getAnnotations' => 'application#CORS_preflight', via: [:options], defaults: {format: :json}
  match 'annotations' => 'application#CORS_preflight', via: [:options], defaults: {format: :json}
  match 'annotations/*all' => 'application#CORS_preflight', via: [:options], defaults: {format: :json}
  match 'lists' => 'application#CORS_preflight', via: [:options], defaults: {format: :json}
  match 'layers' => 'application#CORS_preflight', via: [:options], defaults: {format: :json}
  match 'getAnnotationsViaList' => 'application#CORS_preflight', via: [:options], defaults: {format: :json}
  match 'resequenceList' => 'application#CORS_preflight', via: [:options], defaults: {format: :json}
end

app/models/annotation_layer.rb
class AnnotationLayer < ApplicationRecord
  validates :layer_id, uniqueness: true

  has_and_belongs_to_many :groups

  has_many :webacls, foreign_key: "resource_id"

  def to_iiif
    iiif = Hash.new
    iiif['@id'] = layer_id
    iiif['@type'] = layer_type
    iiif['@context'] = "http://iiif.io/api/presentation/2/context.json"
    iiif['label'] = label if !label.blank?
    iiif['motivation'] = motivation if !motivation.blank?
    iiif['license'] = license if !license.blank?
    iiif['description'] = description if !description.blank?
    iiif['otherContent'] = LayerListsMap.getListsForLayer layer_id
    iiif
  end

  def to_version_content
    version_content = Hash.new
    version_content['@id'] = layer_id
    version_content['@type'] = layer_type
    version_content['@context'] = "http://iiif.io/api/presentation/2/context.json"
    version_content['label'] = label if !label.blank?
    version_content['motivation'] = motivation if !motivation.blank?
    version_content['license'] = license if !license.blank?
    version_content['description'] = description if !description.blank?
    version_content['otherContent'] = LayerListsMap.getListsForLayer layer_id
    version_content
  end

end

app/controllers/annotation_layer_controller.rb
class AnnotationLayerController < ApplicationController
  skip_before_action :verify_authenticity_token
  respond_to :html, :json

  # GET /layer
  # GET /layer.json
  def index
    @annotation_layers = AnnotationLayer.all
    respond_to do |format|
      format.html #index.html.erb
      iiif = []
      @annotation_layers.each do |annotation_layer|
        iiif << annotation_layer.to_iiif
      end
      iiif.to_json
      format.json {render json: iiif}
    end
  end

  # GET /layer/1
  # GET /layer/1.json
  def show
    #@ru = request.original_url
    @ru = request.protocol + request.host_with_port + "/layers/#{params['id']}"
    @annotation_layer = AnnotationLayer.where(layer_id: @ru).first
    #authorize! :show, @annotation_layer
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @annotation_layer.to_iiif }
    end
  end

  # POST /layer
  # POST /layer.json
  def create
    @layerIn = JSON.parse(params.to_json)
    @layer = Hash.new
    #@ru = request.original_url
    @ru = request.original_url.split('?').first
    @ru += '/'   if !@ru.end_with? '/'
    @layer['layer_id'] = @ru + SecureRandom.uuid
    @layer['layer_type'] = @layerIn['@type']
    @layer['label'] = @layerIn['label']
    @layer['motivation'] = @layerIn['motivation']
    #@layer['description'] = @layerIn['description']
    @layer['license'] = @layerIn['license']
    @layer['version'] = 1
    @annotation_layer = AnnotationLayer.new(@layer)

    #authorize! :create, @annotation_layer
    request.format = "json"
    respond_to do |format|
      if @annotation_layer.save
        format.html { redirect_to @annotation_layer, notice: 'Annotation layer was successfully created.' }
        format.json { render json: @annotation_layer.to_iiif, status: :created, location: @annotation_layer }
      else
        format.html { render action: "new" }
        format.json { render json: @annotation_layer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /layer/1
  # PUT /layer/1.json

  def update
    @annotationLayerIn = JSON.parse(params.to_json)
    @problem = ''
    if !validate_annotationLayer @annotationLayerIn
      errMsg = "Annotation Layer not valid and could not be updated: " + @problem
      render :json => { :error => errMsg },
             :status => :unprocessable_entity
    else

      @annotationLayer = AnnotationLayer.where(layer_id: @annotationLayerIn['@id']).first
      #authorize! :update, @annotationLayer

      if @annotationLayer.version.nil? ||  @annotationLayer.version < 1
        @annotationLayer.version = 1
      end

      if !version_layer @annotationLayer
        errMsg = "Annotation Layer could not be updated: " + @problem
        render :json => { :error => errMsg },
               :status => :unprocessable_entity
      end

      newVersion = @annotationLayer.version + 1
      request.format = "json"
      respond_to do |format|
        if @annotationLayer.update_attributes(
            :layer_id => @annotationLayerIn['@id'],
            :layer_type => @annotationLayerIn['@type'],
            :label => @annotationLayerIn['label'],
            :motivation => @annotationLayerIn['motivation'],
            :license => @annotationLayerIn['license'],
            :description => @annotationLayerIn['description'],
            :version => newVersion
        )
          format.html { redirect_to @annotationLayer, notice: 'AnnotationLayer was successfully updated.' }
          format.json { render json: @annotationLayer.to_iiif, status: 200 }
        else
          format.html { render action: "edit" }
          format.json { render json: @annotationLayer.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /layer/1
  # DELETE /layer/1.json
  def destroy
    #@ru = request.original_url
    @ru = request.protocol + request.host_with_port + "/layers/#{params['id']}"
    @annotationLayer = AnnotationLayer.where(layer_id: @ru).first
    #authorize! :delete, @annotation_layer
    if @annotationLayer.version.nil? ||  @annotationLayer.version < 1
      @annotationLayer.version = 1
    end
    if !version_layer @annotationLayer
      errMsg = "Annotation Layer could not be updated: " + @problem
      render :json => { :error => errMsg },
             :status => :unprocessable_entity
    end
    @annotationLayer.destroy
    request.format = "json"
    respond_to do |format|
      format.html { redirect_to annotation_layers_url }
      format.json { head :no_content }
    end
  end

  protected

  def validate_annotationLayer annotationLayer
    valid = true
    if !annotationLayer['@type'].to_s.downcase! == 'sc:layer'
      @problem = "invalid '@type': #{anotationLayer['@type']}"
      valid = false
    end
    if annotationLayer['label'].nil?
      @problem = "missing 'label'"
      valid = false
    end
    valid
  end

  def version_layer layer
    versioned = true
    @allVersion = Hash.new
    @allVersion['all_id'] = layer.layer_id
    @allVersion['all_type'] = layer.layer_type
    @allVersion['all_version'] = layer.version
    @allVersion['all_content'] = layer.to_version_content
    @annotation_layer_version = AnnoListLayerVersion.new(@allVersion)
    if !@annotation_layer_version.save
      @problem = "versioning for this record failed"
      versioned = false
    end
    versioned
  end

end

app/helpers/annotation_layers_helper.rb
module AnnotationLayersHelper
end

app/views/annotation_layers/_form.html.erb
<%= form_for(@annotation_layer) do |f| %>
  <% if @annotation_layer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@annotation_layer.errors.count, "error") %> prohibited this annotation_layer from being saved:</h2>

      <ul>
      <% @annotation_layer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uri %><br />
    <%= f.text_field :@id, readonly: true, size: 80 %>
    <%= f.hidden_field :id %>
  </div>
  <div class="field">
    <%= f.label :label %><br />
    <%= f.text_field :label, size: 80 %>
  </div>
  <div class="field">
    <%= f.label :motivation %><br />
    <%= f.text_field :motivation %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, cols: 80, rows: 5 %>
  </div>
  <div class="field">
    <%= f.label :attribution %><br />
    <%= f.text_field :attribution, size: 80 %>
  </div>
  <div class="field">
    <%= f.label :license %><br />
    <%= f.text_field :license, size: 80 %>
  </div>
  <div class="actions">
    <br/>
    <p><%= f.submit %></p>
  </div>
<% end %>

app/views/annotation_layers/edit.html.erb
<div class="container">
    <div class="page-header">
        <h1>Editing annotation_layer</h1>
    </div>

    <div class="col-sm-12 col-md-12">
        <%= render 'form' %>

        <%= link_to 'Show', @annotation_layer %> |
        <%= link_to 'Back', annotation_layers_path %>
    </div>
</div>

app/views/annotation_layers/index.html.erb
<!--<div class="container">
    <div class="page-header">
        <h1>Ten Thousand Rooms</h1>
        <%#if !current_user.nil? %>
            <h2>You are logged in as <%#==current_user.uid%></h2>
        <%#end %>
    </div>
    <div class="col-sm-12 col-md-12">

        <p id="notice"><%#= notice %></p>

        <p>
            <b>Welcome to the 10,000 Room Annotation Server back end</b>
        </p>

    </div>
</div>-->

<% if (user_signed_in?) %>
    <script type="text/javascript">
        $('document').ready(function() {
            window.opener.postMessage('{"tgToken":"<%==current_user.tgToken%>","UserId":"<%==current_user.uid%>"}', "*");
            window.close();
        })
    </script>
<% end %>

app/views/annotation_layers/show.html.erb
<div class="container">
    <div class="page-header">
        <h1>Layer: <%= @annotation_layer.label %></h1>
    </div>
    <div class="col-sm-12 col-md-12">

        <p id="notice"><%= notice %></p>

        <p>
            <b>Identifier (URI):</b>
            <%= @annotation_layer['@id'] %>
        </p>

        <p>
            <b>Label:</b>
            <%= @annotation_layer.label %>
        </p>

        <p>
            <b>Motivation:</b>
            <%= @annotation_layer.motivation %>
        </p>

        <p>
            <b>Description:</b>
            <%= @annotation_layer.description %>
        </p>

        <p>
            <b>Attribution:</b>
            <%= @annotation_layer.attribution %>
        </p>

        <p>
            <b>License:</b>
            <%= @annotation_layer.license %>
        </p>


        <%= link_to 'Edit', edit_annotation_layer_path(@annotation_layer) %> |
        <%= link_to 'Back', annotation_layers_path %>
    </div>
</div>